on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        default: '0.0.0.0'
        required: true
        type: string
      create-release:
        type: boolean
        description: "Create Release"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'windows-latest' ]

    steps:
    - uses: actions/checkout@v1

    - name: restore x64
      run: dotnet restore OpenUtau -r win-x64

    - name: build x64
      run: dotnet publish OpenUtau -c Release -r win-x64 --self-contained true -o bin/win-x64 /p:version=${{ inputs.version }}

    - name: add openutau.plugins.builtin
      run: copy OpenUtau.Plugin.Builtin\bin\Release\netstandard2.1\OpenUtau.Plugin.Builtin.dll -Destination bin\win-x64

    #手动添加directml.dll的临时方案
    - name: add directml.dll
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://github.com/xunmengshe/OpenUtau/releases/download/0.0.0.1/DirectML.dll
        file-name: DirectML.dll
        location: ./bin/win-x64/

    - name: compress x64
      run: 7z a OpenUtau-x64-${{ inputs.version }}.zip ./bin/win-x64/*

    - name: download vocoder
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://github.com/xunmengshe/OpenUtau/releases/download/0.0.0.0/nsf_hifigan.dsvocoder
        file-name: nsf_hifigan.dsvocoder
        location: ./
        
    - name: extract vocoder
      run: 7z x -o"./bin/win-x64/Vocoders/nsf_hifigan" ./nsf_hifigan.dsvocoder
        
    - name: download rhythmizer
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://github.com/xunmengshe/OpenUtau/releases/download/0.0.0.0/rhythmizer_zh_opencpop_strict.dsvocoder
        file-name: rhythmizer_zh_opencpop_strict.dsvocoder
        location: ./
    
    - name: extract rhythmizer
      run: 7z x -o"./bin/win-x64/Vocoders/rhythmizer_zh_opencpop_strict" ./rhythmizer_zh_opencpop_strict.dsvocoder
     
    - name: compress x64 DiffsingerPack
      run: 7z a OpenUtau-x64-${{ inputs.version }}-DiffsingerPack.zip ./bin/win-x64/*
     
    - name: Upload artifact x64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: OpenUtau-x64-${{ inputs.version }}.zip
        path: OpenUtau-x64-${{ inputs.version }}.zip
        
    - name: Upload artifact x64 DiffsingerPack
      uses: actions/upload-artifact@v1.0.0
      with:
        name: OpenUtau-x64-${{ inputs.version }}-DiffsingerPack.zip
        path: OpenUtau-x64-${{ inputs.version }}-DiffsingerPack.zip

    - name: Create release
      if: ${{ inputs.create-release }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.version }}
        files: |
          OpenUtau-x64-${{ inputs.version }}.zip
          OpenUtau-x64-${{ inputs.version }}-DiffsingerPack.zip
